# Generated by Django 4.2.2 on 2023-06-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_rename_snacks_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='title',
        ),
    ]
